- name: learning variables
  hosts: localhost
  vars:
   course: "Devops"
   duration: "1 hr"
   tool: "ansible"
  tasks:
   - name: learning ansible avriables
    vars:
     course: "DevopsAWS"
     duration: "1.9 hr"
    ansible.builtin.debug:
    msg: "Hi I am learning {{course}} and {{tool}} for {{duration}}"
   
   
 
