- name: learning variables
  hosts: localhost
  vars:
   course: "Devops"
   duration: "1 hr"
   tool: "ansible"
  tasks:
   - name: learning ansible variables
      vars:
       course: "DevopsAWS"
       duration: "120hrs"
    ansible.builtin.debug:
      msg: "Hi Hello, I am learning {{course}} course and {{tool}} for {{duration}}"
   
 
