- name: learning variables
  hosts: localhost
  vars_files:
  - Vars.yaml
  vars_prompt:
  - name: usrname
    prompt: enter username
    private: false
  - name: password
    prompt: enter password
    private: true
  vars:
   course: "Devops"
   duration: "1 hr"
   tool: "ansible"
  tasks:
   - name: learning ansible avriables
     vars:
      course: "DevopsAWS"
      duration: "1.9 hr"
     ansible.builtin.debug:
       msg: "Hi I am learning {{course}} and {{tool}} for {{duration}}"
   - name: learning ansible all vars
     vars:
      timing: "2 PM"
      city : "Hyderabad"
     ansible.builtin.debug:
       msg: "Hi I am going to Goa at {{timing}} to {{city}}"
   - name: message from file
     ansible.builtin.debug:
      msg: "Hi hello {{wishes}}"  
   - name : message from prompt
     ansible.builtin.debug:
      msg: "credentials are {{usrname}} and password is {{password}}"    
      
   
 
