- name: filters
  hosts: localhost
  vars:
   greeting: "hello good morning"
   list:
    - user: "phani"
    - age: "26"
    - address: "Hyderabad"
  tasks:
   - name: print list
     ansible.builtin.debug:
       msg: "here is the list of variables: {{list}}"
- name: filters
  hosts: localhost
  tasks:
   - name: print course
     ansible.builtin.debug:
       msg: "course is {{course | default ('ansible')}}"
- name: upper
  hosts: localhost
  tasks:
   - name: print upper
     ansible.builtin.debug:
      msg: {{greeting | upper}}