- name: filters
  hosts: localhost
  vars:
   greeting: "hello good morning"
   list:
     user: "phani"
     age: "26"
     address: "Hyderabad"
  tasks:
   - name: print list
     ansible.builtin.debug:
       msg: "here is the list of variables: {{ list }}"
   - name: print list
     ansible.builtin.debug:
       msg: "here is the list of variables: {{ list | dict2items }}"
- name: filters
  hosts: localhost
  tasks:
   - name: print course
     ansible.builtin.debug:
       msg: "course is {{course | default ('ansible')}}"
- name: upper and lower
  hosts: localhost
  vars:
   greeting: "HELLO GOOD morning"
  tasks:
   - name: print upper
     ansible.builtin.debug:
       msg: "{{ greeting | lower }}"

- name: remove duplicate numbers
  hosts: localhost
  vars:
   Numbers: [1,2,2,3,3,4,4,5,6,7,899,120,120,10]
  tasks:
   - name: find duplicates and remove
     ansible.builtin.debug:
      msg: "{{ Numbers | unique }}"
- name: print minumum and maximum age
  hosts: localhost
  vars:
   ages: [23,89,56,89,87]
  tasks:
   - name: print minimun and maximum age from list
     ansible.builtin.debug:
      msg: "maximum age is:{{ ages | max }}, minimum age is:{{ ages | min }}"
    
- name: items to dictionary
  hosts: localhost
  vars:
   my_list:
    - {'key':'Couse', 'value':'python'}
    - {'key':'duration', 'value':'23 hrs'}
    - {'key':'trainer', 'value':'phani'}
  tasks:
  - name: before conversion
    ansible.builtin.debug:
      msg: "{{ my_list }}"
   - name: after conversion
     ansible.builtin.debug:
      msg: "{{my_list | items2dict}}"
