- name: install mysql
  hosts: localhost
  become: yes
  tasks:
   - name: Installing 3 databases
     ansible.builtin.dnf:
      name: "{{item}}"
      state: present
     loop:
      - mysql
      - nginx
      - postfix