- name: loops practice
  hosts: localhost
  vars:
   details:
    - name: "phanidra"
    - Adress: "Hhyderabad"
    - Age: "36"
  tasks:
  - name: print loop values
    ansible.builtin.debug:
     msg: loop: "{{details}}"