- name: loops practice
  hosts: localhost
  vars_prompt:
   - name: value
     prompt: enter value
  tasks:
  - name: check conditions
    ansible.builtin.debug:
     msg: "given value {{value}} is greater than 10"
     when : value > 10